sonar.projectKey=TU_PROJECT_KEY
sonar.organization=TU_ORGANIZATION_KEY

sonar.projectName=Hogar Patitas

sonar.sources=.
sonar.tests=tests

sonar.exclusions=reports/**,node_modules/**

sonar.sourceEncoding=UTF-8
