sonar.projectName=Hogar Patitas

sonar.sources=.
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.exclusions=\
.github/**,\
node_modules/**,\
reports/**,\
evidencias/**,\
package-lock.json,\
vercel.json

sonar.test.inclusions=tests/**/*.test.js

sonar.javascript.file.suffixes=.js

sonar.css.file.suffixes=.css

sonar.html.file.suffixes=.html
